# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDM_tXkE-rdvSHMLeaZ6vNkzK_OWQwlV
"""

import pandas as pd
import numpy as np
import joblib
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef

# 1. Setup & Data Loading
if not os.path.exists('model'):
    os.makedirs('model')

print("Loading dataset...")
# Ensure 'UCI_Credit_Card.csv' is in the same directory
df = pd.read_csv('UCI_Credit_Card.csv')

# 2. Preprocessing
# Drop ID and separate Target
X = df.drop(['ID', 'default.payment.next.month'], axis=1)
y = df['default.payment.next.month']

# Train-Test Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Scaling (Crucial for Logistic Regression & kNN)
print("Scaling data...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Save the scaler for the Streamlit app
joblib.dump(scaler, 'model/scaler.pkl')

# 3. Model Definition
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(max_depth=5),
    "kNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Random Forest": RandomForestClassifier(n_estimators=100, max_depth=5),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# 4. Training & Evaluation Loop
results = []

print(f"Training {len(models)} models. This may take a minute...\n")

for name, model in models.items():
    print(f"Training {name}...")

    # Use scaled data for distance-based/linear models; raw data for trees
    if name in ["Logistic Regression", "kNN"]:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_prob = model.predict_proba(X_test_scaled)[:, 1]
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

    # Save the trained model
    # filename format: model/logistic_regression.pkl
    filename = f"model/{name.lower().replace(' ', '_')}.pkl"
    joblib.dump(model, filename)

    # Calculate Metrics
    metrics = {
        "ML Model Name": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "AUC": roc_auc_score(y_test, y_prob),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "MCC": matthews_corrcoef(y_test, y_pred)
    }
    results.append(metrics)

# 5. Output Results
comparison_df = pd.DataFrame(results)

print("\n" + "="*50)
print("FINAL MODEL COMPARISON TABLE")
print("="*50)
print(comparison_df.to_string(index=False))
print("="*50)

# Save test sample for Streamlit app
# We include the target so the app can calculate accuracy on upload
test_sample = X_test.head(100).copy()
test_sample['target'] = y_test.head(100).values
test_sample.to_csv('test_sample.csv', index=False)

print("\n[DONE] Models saved in 'model/' folder. Test sample saved as 'test_sample.csv'.")